/* Ruang Tumbuh style reminder: playful-approachable education editorial; Fraunces + DM Sans; bento cards, bright paper blocks, navy trust. */
import { useEffect, useState } from 'react';

import { AnimatePresence, motion } from 'framer-motion';
import AOS from 'aos';
import { ArrowUpRight, CalendarDays, Check, ChevronRight, Compass, Instagram, Menu, MapPin, Sparkles, X } from 'lucide-react';
import './index.css';

const img = {
  hero: '/manus-storage/ruang-tumbuh-hero_d8ae1e4c.png',
  atelier: '/manus-storage/ruang-tumbuh-atelier_b8d6b923.png',
  library: '/manus-storage/ruang-tumbuh-library_e03ee86e.png',
  garden: '/manus-storage/ruang-tumbuh-garden_f24b07c9.png',
  mark: '/manus-storage/ruang-tumbuh-mark_93ac22a8.png',
};

const nav = [
  ['/tentang/', 'Tentang'], ['/program/', 'Program'], ['/cara-belajar/', 'Cara belajar'], ['/cerita/', 'Cerita'], ['/kontak/', 'Kontak'],
];

function Brand() { return <a href="/" className="brand"><img data-aos="fade-in" src={img.mark} alt="" /><span>ruang<br/><em>tumbuh</em></span></a>; }

function Header() {
  const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false); const location = window.location.pathname;
  useEffect(() => { const fn = () => setScrolled(window.scrollY > 20); window.addEventListener('scroll', fn); return () => window.removeEventListener('scroll', fn); }, []);
  return <>
    <header className={`site-header ${location !== '/' ? 'inner-header' : ''} ${scrolled ? 'is-scrolled' : ''}`}><Brand /><nav className="desktop-nav">{nav.map(([href, label]) => <a key={href} href={href} className={location === href ? 'active' : ''}>{label}</a>)}</nav><a className="header-cta" href="/kontak/">Kunjungi sekolah <ArrowUpRight size={16} /></a><button className="menu-toggle" aria-label="Buka menu" onClick={() => setOpen(true)}><Menu /></button></header>
    <AnimatePresence>{open && <motion.div className="mobile-menu" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><div className="mobile-menu-top"><Brand /><button onClick={() => setOpen(false)} aria-label="Tutup menu"><X /></button></div><nav>{nav.map(([href, label]) => <a key={href} href={href} onClick={() => setOpen(false)}>{label}<ChevronRight size={20}/></a>)}</nav><a href="/kontak/" className="button button-yellow" onClick={() => setOpen(false)}>Atur kunjungan <ArrowUpRight size={17}/></a></motion.div>}</AnimatePresence>
  </>;
}

function Footer() { return <footer><div className="footer-main"><div><Brand /><p className="footer-lead">Sekolah yang memberi ruang<br/>untuk anak bertanya, mencoba,<br/>lalu menemukan jalannya.</p></div><div className="footer-links"><div><strong data-aos="fade-up">Jelajah</strong><a href="/tentang/">Tentang kami</a><a href="/program/">Program</a><a href="/cara-belajar/">Cara belajar</a></div><div><strong data-aos="fade-up">Temui kami</strong><p data-aos="fade-up">Jl. Bukit Dago Selatan 18<br/>Bandung 40135</p><a href="mailto:halo@ruangtumbuh.sch.id">halo@ruangtumbuh.sch.id</a><span>Jalur keluarga · RT/2014</span></div></div></div><div className="footer-bottom"><span>© 2026 Ruang Tumbuh. Dibangun dengan rasa ingin tahu.</span><span className="footer-social"><a href="#instagram" aria-label="Instagram"><Instagram size={16}/></a><a href="#maps" aria-label="Lokasi"><MapPin size={16}/></a></span></div></footer>; }

function Page({children, title, intro, accent='blue'}:{children:React.ReactNode;title:React.ReactNode;intro:string;accent?:string}) { return <><Header/><main className={`inner-page page-${accent}`}><section className="page-intro"><div><div className="page-mark"><img data-aos="fade-in" src={img.mark} alt=""/> Ruang Tumbuh, Bandung</div><h1 data-aos="fade-up">{title}</h1></div><p data-aos="fade-up">{intro}</p></section>{children}</main><Footer/></>; }

function Home() { return <><Header/><main><section className="hero"><div className="hero-copy"><div className="page-mark"><img data-aos="fade-in" src={img.mark} alt=""/> Sekolah dasar & menengah · Bandung</div><h1 data-aos="fade-up">Pertanyaan kecil.<br/><span>Dunia</span> yang<br/>terbuka lebar.</h1><p data-aos="fade-up">Ruang Tumbuh adalah sekolah untuk anak-anak yang senang mencari tahu—belajar lewat proyek nyata, percakapan hangat, dan keberanian untuk mencoba lagi.</p><div className="hero-actions"><a data-aos="fade-up" className="button button-yellow" href="/kontak/">Kenali Ruang Tumbuh <ArrowUpRight size={18}/></a><a data-aos="fade-up" className="text-link light" href="/cara-belajar/">Lihat cara kami belajar <ChevronRight size={18}/></a></div></div><div className="hero-art"><img data-aos="fade-in" src={img.hero} alt="Anak-anak berkolaborasi membuat proyek di ruang kelas"/><div className="hero-note"><Sparkles size={16}/><span>Belajar dengan<br/><b data-aos="fade-up">tangan, kepala, hati.</b></span></div></div><div className="hero-sticker">sejak<br/><strong data-aos="fade-up">2014</strong></div></section>
<section className="quick-grid"><div className="quick-intro"><span className="number" data-aos="fade-up">01</span><h2 data-aos="fade-up">Di sini, belajar<br/><i>terasa dekat.</i></h2><p data-aos="fade-up">Kami tidak mengejar jawaban yang seragam. Kami merawat rasa ingin tahu sampai anak menemukan pertanyaannya sendiri.</p><a data-aos="fade-up" className="text-link" href="/tentang/">Cerita kami <ArrowUpRight size={17}/></a></div><div className="quick-card yellow"><span className="number" data-aos="fade-up">02</span><h3 data-aos="fade-up">Project<br/>studio</h3><p data-aos="fade-up">Matematika, sains, bahasa, dan seni bertemu dalam satu proyek yang bisa disentuh.</p><a href="/program/"><ArrowUpRight/></a></div><div className="quick-card photo"><img data-aos="fade-in" src={img.atelier} alt="Tangan siswa membuat model kincir"/><span className="photo-caption" data-aos="fade-up">Yang dibuat tangan,<br/><b data-aos="fade-up">lebih mudah diingat.</b></span></div><div className="quick-card navy"><Compass size={34}/><h3 data-aos="fade-up">Komunitas<br/>yang hadir</h3><p data-aos="fade-up">Guru mengenal nama, cara berpikir, dan pertumbuhan setiap anak.</p><a href="/cara-belajar/">Jelajahi <ArrowUpRight size={16}/></a></div></section>
<section className="home-band"><div><span className="number" data-aos="fade-up">03</span><h2 data-aos="fade-up">Ruang untuk<br/><em>menjadi.</em></h2></div><div className="band-copy"><p data-aos="fade-up">“Anak-anak tidak datang ke sekolah sebagai halaman kosong. Mereka datang membawa cerita, rasa penasaran, dan cara melihat dunia yang khas.”</p><span data-aos="fade-up">— Mira, Kepala Sekolah</span><a data-aos="fade-up" className="button button-outline" href="/tentang/">Kenali pendekatan kami <ArrowUpRight size={17}/></a></div></section>
<section className="visit-strip"><img data-aos="fade-in" src={img.garden} alt="Siswa mengamati tanaman di kebun sekolah"/><div><span className="number" data-aos="fade-up">04</span><h2 data-aos="fade-up">Datang dan rasakan<br/>suasananya.</h2><p data-aos="fade-up">Kunjungan sekolah dibuka setiap Rabu sore untuk keluarga yang ingin melihat kelas berjalan apa adanya.</p><a data-aos="fade-up" className="button button-yellow" href="/kontak/">Atur kunjungan <ArrowUpRight size={17}/></a></div></section></main><Footer/></>; }

function About(){return <Page title={<>Sekolah yang tumbuh<br/><span>bersama anak.</span></>} intro="Ruang Tumbuh berdiri pada 2014 dari keyakinan sederhana: pendidikan yang baik dimulai dari hubungan yang baik." accent="yellow"><section className="story-grid"><div className="story-photo"><img data-aos="fade-in" src={img.library} alt="Siswa membaca di perpustakaan"/><span data-aos="fade-up">Perpustakaan lantai dua, tempat banyak ide bermula.</span></div><div className="story-text"><h2 data-aos="fade-up">Bukan hanya tentang apa yang dipelajari, tapi <em>siapa yang sedang tumbuh.</em></h2><p data-aos="fade-up">Di lereng Dago, kami membangun sekolah kecil dengan perhatian yang besar. Anak-anak belajar dalam kelompok lintas usia, bertemu guru yang mengenal prosesnya, dan punya waktu untuk menyelesaikan sesuatu dengan tuntas.</p><p data-aos="fade-up">Hari-hari kami diisi eksperimen, percakapan, kesalahan yang dibicarakan tanpa malu, dan momen ketika seseorang akhirnya berkata, “Oh, ternyata begini caranya.”</p><div className="stat-row"><div><strong data-aos="fade-up">12</strong><span>tahun menemani<br/>anak bertumbuh</span></div><div><strong data-aos="fade-up">18</strong><span>anak maksimal<br/>per kelompok</span></div></div></div></section><section className="quote-card"><Sparkles/><h2 data-aos="fade-up">“Kami ingin anak pulang membawa lebih banyak pertanyaan daripada saat ia datang.”</h2></section></Page>}

const programs=[['Tumbuh Awal','Usia 4–6 tahun','Rasa aman, permainan bermakna, dan kebiasaan bertanya.'],['Sekolah Dasar','Kelas 1–6','Proyek lintas mata pelajaran yang berangkat dari dunia nyata.'],['Sekolah Menengah','Kelas 7–9','Riset, kolaborasi, dan ruang untuk memilih tantangan sendiri.']];
function Programs(){return <Page title={<>Program yang<br/><span>mengajak bergerak.</span></>} intro="Setiap jenjang punya ritme yang berbeda. Yang sama: anak selalu menjadi pemilik proses belajarnya." accent="coral"><section className="program-list">{programs.map(([title,age,desc],i)=><motion.div className="program-item" key={title} whileHover={{x:8}}><span className="program-no">0{i+1}</span><div><h2 data-aos="fade-up">{title}</h2><span className="pill" data-aos="fade-up">{age}</span></div><p data-aos="fade-up">{desc}</p><ArrowUpRight/></motion.div>)}</section><section className="program-callout"><div><span className="number" data-aos="fade-up">LAB</span><h2 data-aos="fade-up">Setiap Jumat,<br/><em>hari untuk membuat.</em></h2></div><img data-aos="fade-in" src={img.atelier} alt="Siswa mengerjakan proyek di studio"/></section></Page>}

function Method(){return <Page title={<>Belajar bukan<br/><span>duduk diam.</span></>} intro="Kami merancang pengalaman belajar yang membuat anak bergerak dari rasa penasaran menuju karya yang bisa dibagikan." accent="blue"><section className="method-grid"><div className="method-large"><span className="number" data-aos="fade-up">01</span><h2 data-aos="fade-up">Mulai dari<br/><em>pertanyaan.</em></h2><p data-aos="fade-up">“Mengapa bayangan berubah panjang?” bisa menjadi pelajaran tentang cahaya, pengukuran, dan cara menyampaikan temuan.</p></div><div className="method-small yellow"><span className="number" data-aos="fade-up">02</span><h3 data-aos="fade-up">Coba<br/>bersama</h3><p data-aos="fade-up">Ide tumbuh lebih cepat saat dikerjakan bersama orang lain.</p></div><div className="method-small photo"><img data-aos="fade-in" src={img.garden} alt="Siswa belajar di kebun"/></div><div className="method-small navy"><span className="number" data-aos="fade-up">03</span><h3 data-aos="fade-up">Bagikan<br/>temuan</h3><p data-aos="fade-up">Presentasi bukan ujian akhir, tapi kesempatan untuk didengar.</p></div></section><section className="steps"><div><span>01</span><b data-aos="fade-up">Observe</b><p data-aos="fade-up">Melihat dekat sebelum menyimpulkan.</p></div><div><span>02</span><b data-aos="fade-up">Make</b><p data-aos="fade-up">Membuat versi pertama, lalu mengujinya.</p></div><div><span>03</span><b data-aos="fade-up">Reflect</b><p data-aos="fade-up">Menamai apa yang berubah di dalam diri.</p></div></section></Page>}

function Stories(){return <Page title={<>Yang tumbuh,<br/><span>punya cerita.</span></>} intro="Catatan kecil dari ruang kelas, kebun, studio, dan percakapan yang terus bergerak." accent="yellow"><section className="stories-grid"><article className="story-feature"><img data-aos="fade-in" src={img.garden} alt="Siswa di kebun sekolah"/><div><span data-aos="fade-up">Jurnal kebun · 12 Mei 2026</span><h2 data-aos="fade-up">Ketika satu biji mengajarkan kami tentang kesabaran.</h2><a data-aos="fade-up" className="text-link" href="/cerita-kebun/">Baca cerita <ArrowUpRight size={17}/></a></div></article><article className="story-note"><CalendarDays/><span data-aos="fade-up">Agenda keluarga</span><h3 data-aos="fade-up">Open Studio<br/>Rabu, 16.00</h3><p data-aos="fade-up">Lihat proyek yang sedang dikerjakan dan bertemu dengan guru pendamping.</p><a href="/kontak/">Daftar kunjungan <ArrowUpRight size={17}/></a></article></section></Page>}

function StoryDetail(){return <><Header/><main className="article-page"><div className="article-back"><a data-aos="fade-up" href="/cerita/"><ChevronRight size={16} style={{transform:'rotate(180deg)'}}/> Kembali ke cerita</a></div><article><div className="article-meta" data-aos="fade-up"><span>Jurnal kebun</span><span>12 Mei 2026</span><span>4 menit membaca</span></div><h1 data-aos="fade-up">Ketika satu biji<br/><em>mengajarkan kami</em><br/>tentang kesabaran.</h1><p className="article-dek" data-aos="fade-up">Pagi itu, kami datang ke kebun dengan satu pertanyaan sederhana: apa yang sebenarnya dibutuhkan sebuah benih untuk mulai percaya pada dunia?</p><img className="article-hero" data-aos="fade-in" src={img.garden} alt="Siswa mengamati tanaman di kebun sekolah"/><div className="article-body"><div className="article-aside" data-aos="fade-up"><span className="number">CATATAN 01</span><p>Ditulis dari kebun belakang, setelah hujan pertama di bulan Mei.</p></div><div><p data-aos="fade-up">Kami menanam dua puluh empat biji kacang hijau di pagi yang masih basah. Anak-anak menuliskan perkiraan mereka di kertas kecil: tiga hari, lima hari, mungkin seminggu. Semua terdengar masuk akal. Semua ingin segera terbukti.</p><p data-aos="fade-up">Hari ketiga, belum ada apa-apa. Hari kelima, masih tanah. Beberapa anak mulai menggali pelan-pelan, sekadar untuk memastikan benihnya masih ada. Kami bicara tentang menunggu—bukan sebagai kegiatan pasif, tapi sebagai cara memperhatikan.</p><blockquote data-aos="fade-up">“Kalau kita terus membongkar tanahnya, kapan akarnya punya waktu untuk tumbuh?”</blockquote><p data-aos="fade-up">Pertanyaan itu mengubah cara kami melihat kebun. Kami membuat jadwal pengamatan, menggambar perubahan kecil, dan belajar membedakan antara tidak terjadi apa-apa dengan belum terlihat apa-apa.</p><p data-aos="fade-up">Pada hari kedelapan, satu lengkung hijau muncul. Tidak dramatis. Tidak serempak. Hanya satu tunas kecil yang membuat seluruh kelompok berjongkok lebih dekat.</p><img className="article-inline-image" data-aos="fade-in" src={img.atelier} alt="Tangan siswa mengerjakan proyek dengan bahan sederhana"/><p data-aos="fade-up">Mungkin begitulah belajar sering bekerja. Ia tidak selalu datang sebagai lompatan besar. Kadang ia muncul sebagai garis hijau yang nyaris luput, lalu membuat kita mengubah pertanyaan berikutnya.</p><div className="article-signoff" data-aos="fade-up"><span>— Mira</span><p>Kepala Sekolah, Ruang Tumbuh</p></div></div></div></article></main><Footer/></>}

function Contact(){return <Page title={<>Mari mulai dari<br/><span>sebuah kunjungan.</span></>} intro="Datang untuk melihat ruang kami, mendengar cerita guru, dan bertanya apa pun yang ingin Anda ketahui." accent="coral"><section className="contact-grid"><div className="contact-card"><span className="number" data-aos="fade-up">KUNJUNGAN SEKOLAH</span><h2 data-aos="fade-up">Rabu sore<br/>pukul 16.00</h2><p data-aos="fade-up">Perjalanan singkat selama 60 menit bersama tim penerimaan kami. Anak-anak boleh ikut.</p><a data-aos="fade-up" className="button button-yellow" href="mailto:halo@ruangtumbuh.sch.id?subject=Kunjungan sekolah">Kirim minat kunjungan <ArrowUpRight size={18}/></a></div><form onSubmit={(e)=>e.preventDefault()}><label data-aos="fade-up">Nama orang tua<input placeholder="Nama lengkap"/></label><label data-aos="fade-up">Nama anak<input placeholder="Nama panggilan"/></label><label data-aos="fade-up">Email atau WhatsApp<input placeholder="Untuk konfirmasi jadwal"/></label><button className="button button-navy" type="submit">Saya ingin berkunjung <ArrowUpRight size={18}/></button></form></section><section className="contact-address"><MapPin/><div><b data-aos="fade-up">Ruang Tumbuh</b><p data-aos="fade-up">Jl. Bukit Dago Selatan 18, Bandung 40135</p></div><a href="#maps">Buka peta <ArrowUpRight size={16}/></a></section></Page>}

function NotFound(){return <Page title={<>Halaman ini sedang<br/><span>mencari jalan.</span></>} intro="Coba kembali ke beranda dan mulai dari sana."><a data-aos="fade-up" className="button button-yellow" href="/">Kembali ke beranda <ArrowUpRight size={18}/></a></Page>}
export default function App(){ const page = document.body.dataset.page || 'home'; useEffect(() => { AOS.init({ duration: 650, easing: 'ease-out-cubic', once: true, offset: 56, disable: () => window.matchMedia('(prefers-reduced-motion: reduce)').matches }); AOS.refreshHard(); }, []); if(page === 'about') return <About/>; if(page === 'programs') return <Programs/>; if(page === 'method') return <Method/>; if(page === 'stories') return <Stories/>; if(page === 'contact') return <Contact/>; if(page === 'story-detail') return <StoryDetail/>; return <Home/>; }
